import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { hash } from '../../.fanta/hash'
import { Providers } from '@/components/utilities/providers/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="image/svg+xml" href={`icons/sprite.${hash}.svg`} />
      </head>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
