// This file is generated by yarn workspace web run gen:illustrations:types. Don't edit it manually.

export type IllustrationPath =
	| '/illustrations/gold-coins.svg'
	| '/illustrations/heart-social.svg'
	| '/illustrations/key.svg'
	| '/illustrations/lightning.svg'
	| '/illustrations/money-bag.svg'
	| '/illustrations/money.svg'
	| '/illustrations/reveal.svg'
	| '/illustrations/slot.svg';
